/**
 * GEO-optimized service catalog.
 * Each page answers: what / who / benefits / architecture / process / FAQ / alternatives / ROI.
 */

function faq(question, answer) {
  return { question, answer };
}

export const SERVICES = [
  {
    slug: 'ai-agents',
    title: 'AI Agents Development',
    shortTitle: 'AI Agents',
    eyebrow: 'Intelligent systems',
    summary:
      'Production-grade AI agents that research, decide, call tools, and complete multi-step work across your stack.',
    whoFor:
      'Operations, support, sales, and product teams that need reliable automation beyond single-prompt chatbots.',
    problems: [
      'Repetitive multi-step workflows still depend on humans switching between tools.',
      'Chatbots answer questions but cannot take safe, auditable actions.',
      'Prompt-only prototypes fail when tools, permissions, or edge cases appear.',
      'Leaders cannot measure accuracy, latency, or cost of AI experiments.',
    ],
    benefits: [
      'Agents that plan, use tools, and escalate to humans when confidence is low.',
      'Clear guardrails: roles, allowlists, approval gates, and audit trails.',
      'Integration with CRM, ticketing, ERP, Slack, email, and internal APIs.',
      'Eval harnesses so quality improves with every release, not every hope.',
    ],
    technologies: ['OpenAI Agents / Responses API', 'Anthropic', 'LangGraph', 'MCP', 'n8n', 'Node.js', 'Firebase', 'PostgreSQL'],
    architecture: [
      'Orchestrator agent with typed tool contracts and retry policies.',
      'Memory layers: short-term session state + long-term retrieval when needed.',
      'Policy layer for permissions, PII redaction, and human approval.',
      'Observability: traces, token/cost meters, and failure taxonomies.',
    ],
    process: [
      'Define jobs-to-be-done and success metrics (time saved, CSAT, accuracy).',
      'Map tools, data access, and risk tiers (read-only vs write actions).',
      'Build a thin vertical slice with eval cases from real tickets.',
      'Hardening: rate limits, fallbacks, monitoring, and runbooks.',
      'Roll out with shadow mode → supervised → autonomous where safe.',
    ],
    comparison:
      'Unlike generic chatbot widgets, our agents are engineered as software systems: typed tools, state machines, evals, and operational controls. Unlike no-code-only agents, we design for enterprise permissions, auditability, and maintainability.',
    roi: 'Typical clients cut handling time 40–90% on targeted workflows and reclaim dozens of hours per week once agents own the repetitive path.',
    faqs: [
      faq('What is an AI agent?', 'An AI agent is software that uses a model to plan steps, call tools/APIs, and complete a goal with memory and guardrails—not just a single chat reply.'),
      faq('Who is AI agent development for?', 'Teams with repeatable multi-step work in support, ops, sales, finance, or internal IT that still requires judgment plus system actions.'),
      faq('How do you keep agents safe?', 'We isolate tools, require approvals for high-risk writes, log every action, redact sensitive data, and keep humans in the loop where needed.'),
      faq('How long does an agent MVP take?', 'A focused production pilot usually lands in 3–8 weeks depending on integrations and compliance constraints.'),
    ],
    metaDescription:
      'Build production AI agents with tool use, guardrails, evals, and integrations. LeftSideDev designs agents that actually complete work.',
  },
  {
    slug: 'rag-development',
    title: 'RAG Systems Development',
    shortTitle: 'RAG Systems',
    eyebrow: 'Knowledge AI',
    summary:
      'Retrieval-Augmented Generation systems that answer from your private knowledge with citations, freshness, and access control.',
    whoFor:
      'Companies whose truth lives in docs, tickets, wikis, PDFs, and databases—and need accurate AI answers staff can trust.',
    problems: [
      'Models hallucinate when they lack grounded company context.',
      'Knowledge is scattered across Drive, Notion, Confluence, and inboxes.',
      'Employees waste hours searching for the same policies and playbooks.',
      'Naive RAG demos break on permissions, chunking, and stale content.',
    ],
    benefits: [
      'Cited answers grounded in approved sources.',
      'Hybrid search (keyword + vectors) tuned to your corpus.',
      'Document pipelines with chunking strategies and freshness jobs.',
      'Role-based retrieval so users only see what they may see.',
    ],
    technologies: ['OpenAI Embeddings', 'pgvector', 'Firebase', 'LangChain/LangGraph', 'Elastic/Meilisearch', 'Python/Node', 'Cloud Storage'],
    architecture: [
      'Ingestion: parse → chunk → embed → index with metadata (source, ACL, version).',
      'Retriever: hybrid search + re-ranking + metadata filters.',
      'Generator: grounded prompts with citation requirements.',
      'Feedback loop: thumbs-down → dataset → eval regressions.',
    ],
    process: [
      'Audit corpus quality and access rules.',
      'Prototype retrieval quality before fancy UI.',
      'Ship an internal assistant with citation UX.',
      'Add connectors, re-indexing, and admin controls.',
      'Measure groundedness and deflection from human experts.',
    ],
    comparison:
      'Fine-tuning alone rarely solves private knowledge freshness. Pure search lacks synthesis. Production RAG combines retrieval quality, permissions, and generation discipline.',
    roi: 'Knowledge workers typically save 2–6 hours/week; support teams raise first-contact resolution when answers are grounded and cited.',
    faqs: [
      faq('What is RAG?', 'Retrieval-Augmented Generation fetches relevant documents at query time and conditions the model on that evidence, reducing hallucinations.'),
      faq('Do we need a vector database?', 'Often yes for semantic search, but we also evaluate hybrid keyword search and may start with Postgres + pgvector.'),
      faq('How do you handle permissions?', 'We store ACL metadata with chunks and filter retrieval by the authenticated user’s roles.'),
      faq('What content works best?', 'Structured policies, SOPs, product docs, and cleaned ticket macros outperform messy scanned PDFs—though we can improve both.'),
    ],
    metaDescription:
      'Custom RAG development with hybrid search, citations, ACLs, and evaluation. Turn company knowledge into trustworthy AI answers.',
  },
  {
    slug: 'mcp-development',
    title: 'MCP Integrations',
    shortTitle: 'MCP Integrations',
    eyebrow: 'Tooling for AI',
    summary:
      'Model Context Protocol servers and clients that securely expose your tools, data, and workflows to AI assistants and agents.',
    whoFor:
      'Product and platform teams standardizing how AI tools connect to internal systems without one-off brittle plugins.',
    problems: [
      'Every AI tool needs a custom integration, creating maintenance debt.',
      'Credentials and scopes are copied into prompts or random scripts.',
      'Agents cannot reliably discover and call enterprise capabilities.',
      'Security reviews block AI projects without a clear tool boundary.',
    ],
    benefits: [
      'Standardized tool interfaces for Cursor, Claude, and custom agents.',
      'Centralized auth, scopes, and audit logging for AI tool use.',
      'Faster onboarding of new AI clients onto the same MCP surface.',
      'Cleaner separation between model reasoning and system side effects.',
    ],
    technologies: ['MCP', 'TypeScript', 'Node.js', 'OAuth/OIDC', 'OpenAPI', 'Firebase', 'Docker'],
    architecture: [
      'MCP servers wrapping business capabilities as typed tools/resources.',
      'Auth gateway: short-lived tokens, least privilege, per-tool scopes.',
      'Client adapters for IDEs, chat UIs, and backend agent runtimes.',
      'Telemetry on tool invocations for cost, errors, and misuse detection.',
    ],
    process: [
      'Inventory the tools AI should access (read vs write).',
      'Define schemas, error contracts, and safety policies.',
      'Implement MCP servers with tests and sandbox credentials.',
      'Connect preferred clients and validate end-to-end agent flows.',
      'Document for internal developers and security stakeholders.',
    ],
    comparison:
      'Ad-hoc function calling works for demos. MCP creates a reusable, reviewable integration layer multiple AI clients can share.',
    roi: 'Teams usually cut new AI-tool integration time from weeks to days once a core MCP catalog exists.',
    faqs: [
      faq('What is MCP?', 'Model Context Protocol is a standard for exposing tools and context to AI clients in a structured, interoperable way.'),
      faq('Is MCP only for IDEs?', 'No. We use it for IDEs and production agents that need the same governed tool surface.'),
      faq('Can MCP wrap our existing APIs?', 'Yes—most projects wrap OpenAPI/REST/GraphQL services with policy and logging.'),
      faq('How do you secure MCP servers?', 'Network isolation, authenticated clients, scoped tokens, input validation, and full audit trails.'),
    ],
    metaDescription:
      'MCP development and integrations for secure AI tool access. Expose APIs and workflows to agents with governance.',
  },
  {
    slug: 'web-development',
    title: 'Web Application Development',
    shortTitle: 'Web Applications',
    eyebrow: 'Product engineering',
    summary:
      'Fast, accessible web applications—dashboards, customer portals, and marketing systems engineered for performance and SEO.',
    whoFor: 'Startups and enterprises that need dependable web products, not throwaway landing page templates.',
    problems: [
      'Legacy frontends are slow, inaccessible, or impossible to iterate.',
      'Marketing and product sites fight SEO and Core Web Vitals.',
      'Teams ship features without shared design systems or auth patterns.',
    ],
    benefits: [
      'Modern React/Vite stacks with clean architecture.',
      'Performance budgets, lazy loading, and image discipline.',
      'Accessible UI (WCAG AA) and semantic structure for SEO/GEO.',
      'Integrations with Firebase, APIs, analytics, and AI features.',
    ],
    technologies: ['React', 'Vite', 'TypeScript', 'Tailwind CSS', 'Firebase', 'Node.js', 'PostgreSQL'],
    architecture: [
      'Component-driven UI with clear domain boundaries.',
      'Auth + role-aware routing.',
      'API layer with typed contracts and error handling.',
      'Observability and environment-based configuration.',
    ],
    process: ['Discovery & UX map', 'Architecture spike', 'Iterative delivery', 'Hardening & launch', 'Handover'],
    comparison: 'Agencies often optimize for slides. We optimize for maintainable software your team can own.',
    roi: 'Faster release cycles and fewer production defects typically pay back the build within one or two quarters.',
    faqs: [
      faq('Do you build marketing sites and apps?', 'Yes—promotional surfaces and authenticated products, with the right rendering strategy for each.'),
      faq('SSR or SPA?', 'We choose static, SSR, or SPA based on SEO needs, personalization, and hosting constraints.'),
      faq('Can you modernize an existing app?', 'Yes—strangler migrations are common when a rewrite would be too risky.'),
    ],
    metaDescription:
      'Custom web application development with React, performance, accessibility, and AI-ready architecture.',
  },
  {
    slug: 'mobile-development',
    title: 'Mobile Application Development',
    shortTitle: 'Mobile Applications',
    eyebrow: 'iOS & Android',
    summary: 'Cross-platform and native-feeling mobile apps with offline resilience, push, and secure backend integration.',
    whoFor: 'Businesses that need consumer or field apps with reliable sync and backend services.',
    problems: [
      'Separate native teams slow delivery for MVP validation.',
      'Offline and sync edge cases frustrate field users.',
      'Push, auth, and store compliance become afterthoughts.',
    ],
    benefits: [
      'Flutter or React Native strategies matched to your roadmap.',
      'Secure auth, offline caches, and background sync patterns.',
      'Analytics and crash reporting from day one.',
      'Optional AI features: on-device assist, voice, smart search.',
    ],
    technologies: ['Flutter', 'React Native', 'Firebase', 'Node.js', 'Stripe', 'Push (FCM/APNs)'],
    architecture: ['Client app + BaaS/API', 'Offline-first data layer', 'Secure session management', 'Feature flags for gradual rollout'],
    process: ['Product definition', 'UX flows', 'MVP build', 'Store submission', 'Iterate from analytics'],
    comparison: 'We avoid one-size frameworks dogma—choose the stack that fits team skills and product lifespan.',
    roi: 'Cross-platform MVPs often launch 30–50% faster than dual native teams for the first release.',
    faqs: [
      faq('Flutter or React Native?', 'We recommend based on UI complexity, existing web talent, and long-term hiring plans.'),
      faq('Do you publish to the stores?', 'Yes—we prepare assets, privacy labels, and submission checklists.'),
    ],
    metaDescription: 'Mobile app development for iOS and Android with Firebase, offline sync, and AI-ready features.',
  },
  {
    slug: 'firebase-development',
    title: 'Firebase Development',
    shortTitle: 'Firebase',
    eyebrow: 'Backend platform',
    summary:
      'Auth, Firestore, Functions, Hosting, and Storage architectures that scale multi-tenant products without accidental complexity.',
    whoFor: 'Teams building SaaS, CMS, or mobile backends who want Firebase done correctly—security rules included.',
    problems: [
      'Security rules are too open or too brittle.',
      'Multi-tenant data models leak across customers.',
      'Functions grow into an untested monolith.',
    ],
    benefits: [
      'Hardened Auth + App Check patterns.',
      'Clear Firestore data models and indexes.',
      'Callable/HTTP functions with billing and role gates.',
      'Hosting pipelines and environment separation.',
    ],
    technologies: ['Firebase Auth', 'Firestore', 'Cloud Functions', 'Hosting', 'Storage', 'App Check', 'Extensions'],
    architecture: ['Hub vs external Firebase patterns', 'Tenant isolation', 'Server-side privileged operations', 'Emulator-first local workflows'],
    process: ['Threat model', 'Data model', 'Rules + Functions', 'CI deploy', 'Load & cost review'],
    comparison: 'Firebase is fast until schema and rules are neglected. We treat it as production infrastructure.',
    roi: 'Correct Firebase architecture avoids expensive rewrites when the first enterprise customer arrives.',
    faqs: [
      faq('Is Firebase right for enterprise?', 'Often yes for the right workloads—especially with careful tenancy, App Check, and privileged backends.'),
      faq('Can you rescue an existing Firebase app?', 'Yes—rules audits and data migrations are a frequent engagement.'),
    ],
    metaDescription: 'Expert Firebase development: Auth, Firestore, Functions, security rules, and multi-tenant architecture.',
  },
  {
    slug: 'react-development',
    title: 'React Development',
    shortTitle: 'React',
    eyebrow: 'Frontend excellence',
    summary: 'React engineering for complex UIs: design systems, performance, accessibility, and maintainable state.',
    whoFor: 'Product teams that need senior React delivery without the thrash of junior-only greenfield builds.',
    problems: ['Spaghetti state', 'Slow renders', 'Inconsistent UI', 'No test or a11y culture'],
    benefits: ['Modern React patterns', 'Design system foundations', 'Code splitting & UX polish', 'AI-enhanced product surfaces'],
    technologies: ['React 19', 'Vite', 'TypeScript', 'TanStack Query', 'Tailwind', 'Testing Library'],
    architecture: ['Feature folders', 'Server/client boundaries when needed', 'Typed API clients', 'Story-driven UI where useful'],
    process: ['Audit or greenfield plan', 'Foundation', 'Feature delivery', 'Perf & a11y pass', 'Docs'],
    comparison: 'We write React as a long-lived product asset, not a pile of components.',
    roi: 'Cleaner React codebases cut feature lead time and onboarding cost for every engineer who joins later.',
    faqs: [faq('Do you use Next.js?', 'When SSR/SEO justifies it. Many dashboards thrive on Vite SPA + API.'), faq('TypeScript?', 'Default for any non-trivial app.')],
    metaDescription: 'Senior React development for performant, accessible product interfaces and design systems.',
  },
  {
    slug: 'angular-development',
    title: 'Angular Development',
    shortTitle: 'Angular',
    eyebrow: 'Enterprise UI',
    summary: 'Angular applications for enterprises that need structure, RxJS fluency, and long-term maintainability.',
    whoFor: 'Organizations standardized on Angular or migrating large line-of-business apps.',
    problems: ['Outdated Angular versions', 'Overgrown NgModules', 'Inconsistent RxJS patterns'],
    benefits: ['Upgrades and modernization', 'Standalone/signals where appropriate', 'Strict typing and lint gates', 'Performance tuning'],
    technologies: ['Angular', 'RxJS', 'NgRx/Signals', 'TypeScript', 'Jest/Cypress'],
    architecture: ['Domain modules/features', 'Smart/presentational boundaries', 'API facades', 'Auth guards'],
    process: ['Version & dependency audit', 'Upgrade path', 'Feature work', 'Regression suite', 'Handover'],
    comparison: 'Angular shines when governance and structure matter—we lean into that instead of fighting it.',
    roi: 'Modernized Angular apps reduce defect rates and make hiring/training predictable.',
    faqs: [faq('Can you migrate AngularJS?', 'Yes—via strangler patterns and hybrid strategies when needed.')],
    metaDescription: 'Angular development and modernization for enterprise-grade web applications.',
  },
  {
    slug: 'node-development',
    title: 'Node.js Development',
    shortTitle: 'Node.js',
    eyebrow: 'Backend APIs',
    summary: 'Node.js APIs and workers for products, AI tool backends, webhooks, and high-throughput integrations.',
    whoFor: 'Teams that need reliable TypeScript/Node services with clear contracts and ops basics.',
    problems: ['Unstructured Express apps', 'Missing queues/retries', 'Weak auth on webhooks'],
    benefits: ['Typed APIs', 'Background jobs', 'Secure webhook handling', 'Cost-aware AI proxy layers'],
    technologies: ['Node.js', 'TypeScript', 'Fastify/Express', 'PostgreSQL', 'Redis', 'Firebase Functions'],
    architecture: ['Hexagonal-ish modules', 'Idempotent consumers', 'Structured logging', 'Rate limiting'],
    process: ['API design', 'Implementation', 'Load testing', 'Deploy', 'SLOs'],
    comparison: 'We treat Node as production infrastructure with queues, idempotency, and observability—not a script folder.',
    roi: 'Stable APIs unblock parallel frontend/mobile work and reduce incident load.',
    faqs: [faq('Serverless or always-on?', 'We choose based on traffic shape, cold starts, and integration needs.')],
    metaDescription: 'Node.js API and backend development with TypeScript, queues, and AI-ready service layers.',
  },
  {
    slug: 'php-development',
    title: 'PHP Development',
    shortTitle: 'PHP',
    eyebrow: 'Pragmatic backends',
    summary: 'Modern PHP and Laravel engineering for business systems that must stay reliable while evolving.',
    whoFor: 'Companies with Laravel/PHP estates that need features, APIs, or careful modernization.',
    problems: ['Legacy PHP without tests', 'Security patch lag', 'Mixed frameworks'],
    benefits: ['Laravel APIs & apps', 'Hardened auth', 'Queue workers', 'Incremental modernization'],
    technologies: ['PHP 8', 'Laravel', 'MySQL', 'Redis', 'Docker'],
    architecture: ['MVC/domain services', 'Jobs/queues', 'API resources', 'CI pipelines'],
    process: ['Codebase health check', 'Stabilize', 'Deliver features', 'Automate deploys'],
    comparison: 'We do not force a rewrite to Node when PHP already runs the business—unless ROI says so.',
    roi: 'Stabilizing PHP systems often unlocks months of delayed product work at lower risk than a greenfield rewrite.',
    faqs: [faq('Do you still recommend PHP?', 'When the team and domain fit—yes. Stack dogma wastes money.')],
    metaDescription: 'Modern PHP and Laravel development for secure, maintainable business applications.',
  },
  {
    slug: 'custom-software',
    title: 'Custom Software Development',
    shortTitle: 'Custom Software',
    eyebrow: 'Bespoke systems',
    summary: 'Tailored software for workflows that off-the-shelf SaaS cannot model without painful compromise.',
    whoFor: 'Operators with unique processes, compliance needs, or competitive workflows.',
    problems: ['SaaS sprawl and brittle Zapier chains', 'Spreadsheet ops at scale', 'Vendor lock-in'],
    benefits: ['Software shaped to your process', 'Owned data models', 'Integrations on your terms', 'AI where it multiplies value'],
    technologies: ['React', 'Node', 'Firebase', 'PostgreSQL', 'Python', 'Cloud'],
    architecture: ['Discovery-driven domain model', 'Modular services', 'Integration bus', 'Admin + end-user surfaces'],
    process: ['Process mining workshops', 'MVP scope', 'Build', 'Change management', 'Support options'],
    comparison: 'Buy when SaaS fits. Build when the process is the product.',
    roi: 'Custom systems pay off when they remove daily friction that SaaS cannot price.',
    faqs: [faq('Build vs buy?', 'We run a frank build-vs-buy review before writing code.')],
    metaDescription: 'Custom software development for unique business workflows, integrations, and AI-powered operations.',
  },
  {
    slug: 'startup-mvp',
    title: 'Startup MVP Development',
    shortTitle: 'Startup MVP',
    eyebrow: 'Speed with substance',
    summary: 'Lean MVPs that validate demand with production discipline—auth, analytics, and a path to scale.',
    whoFor: 'Founders who need a credible product in weeks, not a disposable prototype.',
    problems: ['Overbuilding', 'Underbuilding security', 'No instrumentation'],
    benefits: ['Scoped MVP roadmap', 'Ship-ready UX', 'Analytics & feedback loops', 'Architecture that can grow'],
    technologies: ['React', 'Firebase', 'Stripe', 'Node', 'AI APIs as differentiators'],
    architecture: ['Modular monolith first', 'Clear domain edges', 'Feature flags', 'Observability lite'],
    process: ['Problem interview synthesis', 'Scope cut', 'Build in sprints', 'Launch', 'Iterate on metrics'],
    comparison: 'We optimize for learning speed without creating irreversible tech debt.',
    roi: 'A focused MVP can validate pricing and retention before you fund a full platform team.',
    faqs: [faq('How fast?', 'Many MVPs ship in 4–10 weeks depending on integrations and compliance.')],
    metaDescription: 'Startup MVP development: ship a lean, measurable product with a clean path to scale.',
  },
  {
    slug: 'automation',
    title: 'Workflow Automation',
    shortTitle: 'Automation',
    eyebrow: 'Ops leverage',
    summary: 'Intelligent automations with n8n, custom workers, and AI steps that remove manual ops without losing control.',
    whoFor: 'Ops and revenue teams drowning in copy-paste across CRMs, sheets, email, and tickets.',
    problems: ['Manual handoffs', 'Fragile zaps', 'No error handling or ownership'],
    benefits: ['Reliable multi-step workflows', 'Human approval steps', 'AI classification/summaries', 'Dashboards for failures'],
    technologies: ['n8n', 'Make', 'Node workers', 'Webhooks', 'OpenAI', 'Firebase', 'Slack/Email'],
    architecture: ['Trigger → enrich → decide → act → notify', 'Idempotency keys', 'Dead-letter handling', 'Secrets vault'],
    process: ['Map current process', 'Automate happy path', 'Add exceptions', 'Monitor', 'Train owners'],
    comparison: 'We combine iPaaS speed with custom code where reliability or AI depth requires it.',
    roi: 'Clients often reclaim 10–40 hours/week on targeted processes and reduce response latency dramatically.',
    faqs: [
      faq('n8n or custom code?', 'Start with n8n for visibility; extract critical paths to code when complexity or scale demands it.'),
      faq('Can automation include AI?', 'Yes—classification, extraction, drafting, and routing with human review gates.'),
    ],
    metaDescription: 'Workflow automation with n8n, custom workers, and AI steps that scale operations safely.',
  },
];

export function getServiceBySlug(slug) {
  return SERVICES.find((service) => service.slug === slug) || null;
}

export function getServicePath(slug) {
  return `/services/${slug}`;
}
