"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.syncDomainIndexes = exports.askOllamaCloud = exports.ensureBootstrapRoot = exports.reportSystemIncident = exports.listCmsTickets = exports.updateCmsTicket = exports.createCmsTicket = exports.markAllNotificationsRead = exports.markNotificationRead = exports.listMyNotifications = exports.listPageAudits = exports.recordPageAudit = exports.importMetaBusinessProfile = exports.createCmsPage = exports.getAiAssistUsage = exports.setAiProviderConfig = exports.runAiAssist = exports.generateLandingDraft = exports.syncSiteAccessDaily = exports.setBillingMonetization = exports.setBillingAccountAddons = exports.assertMarketingSiteAccess = exports.marketingRobots = exports.marketingRss = exports.marketingSitemap = exports.mercadoPagoBillingWebhook = exports.stripeBillingWebhook = exports.setBillingPlanManual = exports.createBillingCheckout = exports.ensureBillingAccount = exports.triggerHostingDeploy = exports.rejectCmsAccess = exports.approveCmsAccess = exports.requestPasswordResetEmail = exports.requestCmsAccess = exports.updateCmsUser = exports.listCmsUsers = exports.generateCmsUserInvitation = exports.deleteCmsUser = exports.createCmsUser = void 0;
const firebase_functions_1 = require("firebase-functions");
(0, firebase_functions_1.setGlobalOptions)({ maxInstances: 10 });
var cmsUsers_js_1 = require("./cmsUsers.js");
Object.defineProperty(exports, "createCmsUser", { enumerable: true, get: function () { return cmsUsers_js_1.createCmsUser; } });
Object.defineProperty(exports, "deleteCmsUser", { enumerable: true, get: function () { return cmsUsers_js_1.deleteCmsUser; } });
Object.defineProperty(exports, "generateCmsUserInvitation", { enumerable: true, get: function () { return cmsUsers_js_1.generateCmsUserInvitation; } });
Object.defineProperty(exports, "listCmsUsers", { enumerable: true, get: function () { return cmsUsers_js_1.listCmsUsers; } });
Object.defineProperty(exports, "updateCmsUser", { enumerable: true, get: function () { return cmsUsers_js_1.updateCmsUser; } });
Object.defineProperty(exports, "requestCmsAccess", { enumerable: true, get: function () { return cmsUsers_js_1.requestCmsAccess; } });
Object.defineProperty(exports, "requestPasswordResetEmail", { enumerable: true, get: function () { return cmsUsers_js_1.requestPasswordResetEmail; } });
Object.defineProperty(exports, "approveCmsAccess", { enumerable: true, get: function () { return cmsUsers_js_1.approveCmsAccess; } });
Object.defineProperty(exports, "rejectCmsAccess", { enumerable: true, get: function () { return cmsUsers_js_1.rejectCmsAccess; } });
var hostingDeploy_js_1 = require("./hostingDeploy.js");
Object.defineProperty(exports, "triggerHostingDeploy", { enumerable: true, get: function () { return hostingDeploy_js_1.triggerHostingDeploy; } });
var billing_js_1 = require("./billing.js");
Object.defineProperty(exports, "ensureBillingAccount", { enumerable: true, get: function () { return billing_js_1.ensureBillingAccount; } });
Object.defineProperty(exports, "createBillingCheckout", { enumerable: true, get: function () { return billing_js_1.createBillingCheckout; } });
Object.defineProperty(exports, "setBillingPlanManual", { enumerable: true, get: function () { return billing_js_1.setBillingPlanManual; } });
Object.defineProperty(exports, "stripeBillingWebhook", { enumerable: true, get: function () { return billing_js_1.stripeBillingWebhook; } });
Object.defineProperty(exports, "mercadoPagoBillingWebhook", { enumerable: true, get: function () { return billing_js_1.mercadoPagoBillingWebhook; } });
var marketingSeo_js_1 = require("./marketingSeo.js");
Object.defineProperty(exports, "marketingSitemap", { enumerable: true, get: function () { return marketingSeo_js_1.marketingSitemap; } });
Object.defineProperty(exports, "marketingRss", { enumerable: true, get: function () { return marketingSeo_js_1.marketingRss; } });
Object.defineProperty(exports, "marketingRobots", { enumerable: true, get: function () { return marketingSeo_js_1.marketingRobots; } });
var marketingEntitlement_js_1 = require("./marketingEntitlement.js");
Object.defineProperty(exports, "assertMarketingSiteAccess", { enumerable: true, get: function () { return marketingEntitlement_js_1.assertMarketingSiteAccess; } });
Object.defineProperty(exports, "setBillingAccountAddons", { enumerable: true, get: function () { return marketingEntitlement_js_1.setBillingAccountAddons; } });
var siteAccessSync_js_1 = require("./siteAccessSync.js");
Object.defineProperty(exports, "setBillingMonetization", { enumerable: true, get: function () { return siteAccessSync_js_1.setBillingMonetization; } });
Object.defineProperty(exports, "syncSiteAccessDaily", { enumerable: true, get: function () { return siteAccessSync_js_1.syncSiteAccessDaily; } });
var aiAssist_js_1 = require("./aiAssist.js");
Object.defineProperty(exports, "generateLandingDraft", { enumerable: true, get: function () { return aiAssist_js_1.generateLandingDraft; } });
Object.defineProperty(exports, "runAiAssist", { enumerable: true, get: function () { return aiAssist_js_1.runAiAssist; } });
Object.defineProperty(exports, "setAiProviderConfig", { enumerable: true, get: function () { return aiAssist_js_1.setAiProviderConfig; } });
Object.defineProperty(exports, "getAiAssistUsage", { enumerable: true, get: function () { return aiAssist_js_1.getAiAssistUsage; } });
var cmsPages_js_1 = require("./cmsPages.js");
Object.defineProperty(exports, "createCmsPage", { enumerable: true, get: function () { return cmsPages_js_1.createCmsPage; } });
var metaImport_js_1 = require("./metaImport.js");
Object.defineProperty(exports, "importMetaBusinessProfile", { enumerable: true, get: function () { return metaImport_js_1.importMetaBusinessProfile; } });
var cmsInbox_js_1 = require("./cmsInbox.js");
Object.defineProperty(exports, "recordPageAudit", { enumerable: true, get: function () { return cmsInbox_js_1.recordPageAudit; } });
Object.defineProperty(exports, "listPageAudits", { enumerable: true, get: function () { return cmsInbox_js_1.listPageAudits; } });
Object.defineProperty(exports, "listMyNotifications", { enumerable: true, get: function () { return cmsInbox_js_1.listMyNotifications; } });
Object.defineProperty(exports, "markNotificationRead", { enumerable: true, get: function () { return cmsInbox_js_1.markNotificationRead; } });
Object.defineProperty(exports, "markAllNotificationsRead", { enumerable: true, get: function () { return cmsInbox_js_1.markAllNotificationsRead; } });
Object.defineProperty(exports, "createCmsTicket", { enumerable: true, get: function () { return cmsInbox_js_1.createCmsTicket; } });
Object.defineProperty(exports, "updateCmsTicket", { enumerable: true, get: function () { return cmsInbox_js_1.updateCmsTicket; } });
Object.defineProperty(exports, "listCmsTickets", { enumerable: true, get: function () { return cmsInbox_js_1.listCmsTickets; } });
Object.defineProperty(exports, "reportSystemIncident", { enumerable: true, get: function () { return cmsInbox_js_1.reportSystemIncident; } });
var bootstrapRoot_js_1 = require("./bootstrapRoot.js");
Object.defineProperty(exports, "ensureBootstrapRoot", { enumerable: true, get: function () { return bootstrapRoot_js_1.ensureBootstrapRoot; } });
var askOllamaCloud_js_1 = require("./askOllamaCloud.js");
Object.defineProperty(exports, "askOllamaCloud", { enumerable: true, get: function () { return askOllamaCloud_js_1.askOllamaCloud; } });
var domainIndex_js_1 = require("./domainIndex.js");
Object.defineProperty(exports, "syncDomainIndexes", { enumerable: true, get: function () { return domainIndex_js_1.syncDomainIndexes; } });
var referralTracking_js_1 = require("./referralTracking.js");
Object.defineProperty(exports, "enableReferralCode", { enumerable: true, get: function () { return referralTracking_js_1.enableReferralCode; } });
Object.defineProperty(exports, "updateReferralCode", { enumerable: true, get: function () { return referralTracking_js_1.updateReferralCode; } });
Object.defineProperty(exports, "toggleReferralEnabled", { enumerable: true, get: function () { return referralTracking_js_1.toggleReferralEnabled; } });
Object.defineProperty(exports, "trackReferralClick", { enumerable: true, get: function () { return referralTracking_js_1.trackReferralClick; } });
Object.defineProperty(exports, "recordReferralConversion", { enumerable: true, get: function () { return referralTracking_js_1.recordReferralConversion; } });
Object.defineProperty(exports, "getReferralAnalytics", { enumerable: true, get: function () { return referralTracking_js_1.getReferralAnalytics; } });
//# sourceMappingURL=index.js.map