"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.setBillingAccountAddons = exports.assertMarketingSiteAccess = exports.marketingRobots = exports.marketingRss = exports.marketingSitemap = exports.mercadoPagoBillingWebhook = exports.stripeBillingWebhook = exports.setBillingPlanManual = exports.createBillingCheckout = exports.ensureBillingAccount = exports.triggerHostingDeploy = exports.deleteCmsUser = exports.createCmsUser = void 0;
const firebase_functions_1 = require("firebase-functions");
(0, firebase_functions_1.setGlobalOptions)({ maxInstances: 10 });
var cmsUsers_js_1 = require("./cmsUsers.js");
Object.defineProperty(exports, "createCmsUser", { enumerable: true, get: function () { return cmsUsers_js_1.createCmsUser; } });
Object.defineProperty(exports, "deleteCmsUser", { enumerable: true, get: function () { return cmsUsers_js_1.deleteCmsUser; } });
var hostingDeploy_js_1 = require("./hostingDeploy.js");
Object.defineProperty(exports, "triggerHostingDeploy", { enumerable: true, get: function () { return hostingDeploy_js_1.triggerHostingDeploy; } });
var billing_js_1 = require("./billing.js");
Object.defineProperty(exports, "ensureBillingAccount", { enumerable: true, get: function () { return billing_js_1.ensureBillingAccount; } });
Object.defineProperty(exports, "createBillingCheckout", { enumerable: true, get: function () { return billing_js_1.createBillingCheckout; } });
Object.defineProperty(exports, "setBillingPlanManual", { enumerable: true, get: function () { return billing_js_1.setBillingPlanManual; } });
Object.defineProperty(exports, "stripeBillingWebhook", { enumerable: true, get: function () { return billing_js_1.stripeBillingWebhook; } });
Object.defineProperty(exports, "mercadoPagoBillingWebhook", { enumerable: true, get: function () { return billing_js_1.mercadoPagoBillingWebhook; } });
var marketingSeo_js_1 = require("./marketingSeo.js");
Object.defineProperty(exports, "marketingSitemap", { enumerable: true, get: function () { return marketingSeo_js_1.marketingSitemap; } });
Object.defineProperty(exports, "marketingRss", { enumerable: true, get: function () { return marketingSeo_js_1.marketingRss; } });
Object.defineProperty(exports, "marketingRobots", { enumerable: true, get: function () { return marketingSeo_js_1.marketingRobots; } });
var marketingEntitlement_js_1 = require("./marketingEntitlement.js");
Object.defineProperty(exports, "assertMarketingSiteAccess", { enumerable: true, get: function () { return marketingEntitlement_js_1.assertMarketingSiteAccess; } });
Object.defineProperty(exports, "setBillingAccountAddons", { enumerable: true, get: function () { return marketingEntitlement_js_1.setBillingAccountAddons; } });
//# sourceMappingURL=index.js.map