export const DEFAULT_VERTICAL = 'generic';

export const VERTICAL_IDS = [
  'generic',
  'psychology',
  'dental',
  'veterinary',
  'legal',
  'medical',
  'beauty',
  'fitness',
  'education',
  'ecommerce',
];

const VERTICAL_ID_SET = new Set(VERTICAL_IDS);

export const VERTICALS = [
  {
    id: 'generic',
    label: { es: 'Genérico / negocio', en: 'Generic / business' },
    description: {
      es: 'Tono neutro para cualquier profesión o emprendimiento.',
      en: 'Neutral tone for any profession or business.',
    },
    defaultSpecialty: { es: '', en: '' },
  },
  {
    id: 'psychology',
    label: { es: 'Psicología / salud mental', en: 'Psychology / mental health' },
    description: {
      es: 'Consultas, terapia y acompañamiento emocional.',
      en: 'Therapy, counseling, and emotional support.',
    },
    defaultSpecialty: { es: 'Psicología clínica', en: 'Clinical psychology' },
  },
  {
    id: 'dental',
    label: { es: 'Odontología', en: 'Dental' },
    description: {
      es: 'Clínica dental y salud bucal.',
      en: 'Dental clinic and oral health.',
    },
    defaultSpecialty: { es: 'Odontología general', en: 'General dentistry' },
  },
  {
    id: 'veterinary',
    label: { es: 'Veterinaria', en: 'Veterinary' },
    description: {
      es: 'Cuidado animal y consultorio veterinario.',
      en: 'Pet care and veterinary clinic.',
    },
    defaultSpecialty: { es: 'Medicina veterinaria', en: 'Veterinary medicine' },
  },
  {
    id: 'legal',
    label: { es: 'Abogados / despacho', en: 'Legal / law firm' },
    description: {
      es: 'Asesoría jurídica y servicios legales.',
      en: 'Legal advice and law services.',
    },
    defaultSpecialty: { es: 'Derecho', en: 'Law' },
  },
  {
    id: 'medical',
    label: { es: 'Salud / consultorio', en: 'Healthcare / clinic' },
    description: {
      es: 'Médicos, nutriólogos, fisioterapia y afines.',
      en: 'Doctors, nutrition, physio, and related care.',
    },
    defaultSpecialty: { es: 'Consulta médica', en: 'Medical consultation' },
  },
  {
    id: 'beauty',
    label: { es: 'Belleza / bienestar', en: 'Beauty / wellness' },
    description: {
      es: 'Estética, spa, barbería y bienestar.',
      en: 'Beauty, spa, barber, and wellness.',
    },
    defaultSpecialty: { es: 'Estética y bienestar', en: 'Beauty and wellness' },
  },
  {
    id: 'fitness',
    label: { es: 'Fitness / coaching', en: 'Fitness / coaching' },
    description: {
      es: 'Entrenamiento, gym y coaching personal.',
      en: 'Training, gym, and personal coaching.',
    },
    defaultSpecialty: { es: 'Entrenamiento personal', en: 'Personal training' },
  },
  {
    id: 'education',
    label: { es: 'Educación / cursos', en: 'Education / courses' },
    description: {
      es: 'Academias, tutorías y programas formativos.',
      en: 'Academies, tutoring, and learning programs.',
    },
    defaultSpecialty: { es: 'Educación', en: 'Education' },
  },
  {
    id: 'ecommerce',
    label: { es: 'Catálogo / tienda', en: 'Catalog / shop' },
    description: {
      es: 'Productos, paquetes y venta con catálogo.',
      en: 'Products, packages, and catalog-led sales.',
    },
    defaultSpecialty: { es: 'Tienda', en: 'Shop' },
  },
];

export function normalizeVertical(value) {
  const id = String(value ?? '').trim().toLowerCase();
  return VERTICAL_ID_SET.has(id) ? id : DEFAULT_VERTICAL;
}

export function getVerticalMeta(value) {
  const id = normalizeVertical(value);
  return VERTICALS.find((item) => item.id === id) ?? VERTICALS[0];
}

export function getVerticalDefaultSpecialty(value, language = 'es') {
  const meta = getVerticalMeta(value);
  const lang = language === 'en' ? 'en' : 'es';
  return String(meta.defaultSpecialty?.[lang] ?? meta.defaultSpecialty?.es ?? '').trim();
}

/** Shared brand/message keys that presets typically customize. */
const VERTICAL_LABEL_OVERRIDES = {
  psychology: {
    es: {
      'placeholders.psychologistName': 'Nombre de la psicóloga',
      'placeholders.specialty': 'Especialidad',
      'placeholders.aboutTagline': 'Cada proceso es único, y mereces ser escuchada con atención y cuidado.',
      'placeholders.aboutBio': 'Biografía profesional.',
      'nav.bookAppointment': 'Reservar cita',
      'contact.subtitle': 'Estoy aquí para acompañarte. Escríbeme o llámame para agendar una primera consulta.',
      'services.defaultTitle': 'Servicios y áreas de atención',
      'services.defaultIntro': 'Temas y acompañamientos que podemos trabajar juntas.',
      'gallery.defaultIntro': 'Un vistazo al espacio y al acompañamiento.',
      'testimonials.subtitle': 'Experiencias compartidas con respeto y confidencialidad.',
      'blog.defaultTitle': 'Blog',
      'blog.defaultIntro': 'Artículos, reflexiones y novedades del consultorio.',
      'booking.whatsappMessage': 'Hola, me gustaría agendar una cita.',
      'booking.mailtoSubject': 'Consulta de cita',
      'phone.whatsappMessage': 'Hola, me gustaría contactarte.',
    },
    en: {
      'placeholders.psychologistName': 'Psychologist name',
      'placeholders.specialty': 'Specialty',
      'placeholders.aboutTagline': 'Every process is unique, and you deserve to be heard with care and attention.',
      'placeholders.aboutBio': 'Professional biography.',
      'nav.bookAppointment': 'Book appointment',
      'contact.subtitle': 'I am here to support you. Write or call me to schedule a first consultation.',
      'services.defaultTitle': 'Services and areas of care',
      'services.defaultIntro': 'Topics and support we can work on together.',
      'gallery.defaultIntro': 'A glimpse of the space and the process.',
      'testimonials.subtitle': 'Experiences shared with respect and confidentiality.',
      'blog.defaultTitle': 'Blog',
      'blog.defaultIntro': 'Articles, reflections, and practice updates.',
      'booking.whatsappMessage': 'Hello, I would like to book an appointment.',
      'booking.mailtoSubject': 'Appointment inquiry',
      'phone.whatsappMessage': 'Hello, I would like to get in touch.',
    },
  },
  dental: {
    es: {
      'placeholders.psychologistName': 'Nombre del dentista',
      'placeholders.specialty': 'Especialidad odontológica',
      'placeholders.aboutTagline': 'Tu sonrisa merece cuidado profesional y cercanía.',
      'nav.bookAppointment': 'Agendar consulta',
      'contact.subtitle': 'Agenda tu revisión o consulta. Estamos para cuidarte la sonrisa.',
      'services.defaultTitle': 'Tratamientos',
      'services.defaultIntro': 'Procedimientos y cuidados para tu salud bucal.',
      'gallery.defaultIntro': 'Conoce el consultorio y nuestro espacio de atención.',
      'testimonials.subtitle': 'Lo que dicen nuestros pacientes.',
      'booking.whatsappMessage': 'Hola, me gustaría agendar una consulta dental.',
      'booking.mailtoSubject': 'Consulta odontológica',
      'phone.whatsappMessage': 'Hola, me gustaría información sobre tratamientos dentales.',
    },
    en: {
      'placeholders.psychologistName': 'Dentist name',
      'placeholders.specialty': 'Dental specialty',
      'placeholders.aboutTagline': 'Your smile deserves professional care and a personal touch.',
      'nav.bookAppointment': 'Book a visit',
      'contact.subtitle': 'Schedule a check-up or consultation. We are here for your smile.',
      'services.defaultTitle': 'Treatments',
      'services.defaultIntro': 'Procedures and care for your oral health.',
      'gallery.defaultIntro': 'Take a look at our clinic and care space.',
      'testimonials.subtitle': 'What our patients say.',
      'booking.whatsappMessage': 'Hello, I would like to book a dental appointment.',
      'booking.mailtoSubject': 'Dental consultation',
      'phone.whatsappMessage': 'Hello, I would like information about dental treatments.',
    },
  },
  veterinary: {
    es: {
      'placeholders.psychologistName': 'Nombre del veterinario',
      'placeholders.specialty': 'Especialidad veterinaria',
      'placeholders.aboutTagline': 'Cuidamos a tus compañeros con profesionalismo y cariño.',
      'nav.bookAppointment': 'Agendar cita',
      'contact.subtitle': 'Escríbenos o llámanos para agendar la visita de tu mascota.',
      'services.defaultTitle': 'Servicios veterinarios',
      'services.defaultIntro': 'Atención preventiva, consultas y cuidados para tu mascota.',
      'gallery.defaultIntro': 'Nuestro consultorio y el espacio pensado para ellos.',
      'testimonials.subtitle': 'Familias que confían en nosotros.',
      'booking.whatsappMessage': 'Hola, me gustaría agendar una cita para mi mascota.',
      'booking.mailtoSubject': 'Cita veterinaria',
      'phone.whatsappMessage': 'Hola, me gustaría información sobre atención veterinaria.',
    },
    en: {
      'placeholders.psychologistName': 'Veterinarian name',
      'placeholders.specialty': 'Veterinary specialty',
      'placeholders.aboutTagline': 'We care for your companions with skill and kindness.',
      'nav.bookAppointment': 'Book a visit',
      'contact.subtitle': 'Write or call us to schedule a visit for your pet.',
      'services.defaultTitle': 'Veterinary services',
      'services.defaultIntro': 'Preventive care, consults, and support for your pet.',
      'gallery.defaultIntro': 'Our clinic and a space designed for pets.',
      'testimonials.subtitle': 'Families who trust us.',
      'booking.whatsappMessage': 'Hello, I would like to book an appointment for my pet.',
      'booking.mailtoSubject': 'Veterinary appointment',
      'phone.whatsappMessage': 'Hello, I would like information about veterinary care.',
    },
  },
  legal: {
    es: {
      'placeholders.psychologistName': 'Nombre del abogado',
      'placeholders.specialty': 'Área de práctica',
      'placeholders.aboutTagline': 'Asesoría clara y estratégica para tus asuntos legales.',
      'nav.bookAppointment': 'Agendar consulta',
      'contact.subtitle': 'Contáctanos para evaluar tu caso y agendar una primera consulta.',
      'services.defaultTitle': 'Áreas de práctica',
      'services.defaultIntro': 'Servicios legales y acompañamiento jurídico.',
      'gallery.defaultIntro': 'Conoce el despacho y nuestro equipo.',
      'testimonials.subtitle': 'Clientes que confían en nuestro criterio.',
      'booking.whatsappMessage': 'Hola, me gustaría agendar una consulta legal.',
      'booking.mailtoSubject': 'Consulta jurídica',
      'phone.whatsappMessage': 'Hola, me gustaría información sobre asesoría legal.',
    },
    en: {
      'placeholders.psychologistName': 'Lawyer name',
      'placeholders.specialty': 'Practice area',
      'placeholders.aboutTagline': 'Clear, strategic counsel for your legal matters.',
      'nav.bookAppointment': 'Book a consultation',
      'contact.subtitle': 'Contact us to review your case and schedule a first consultation.',
      'services.defaultTitle': 'Practice areas',
      'services.defaultIntro': 'Legal services and guidance.',
      'gallery.defaultIntro': 'Meet the firm and our team.',
      'testimonials.subtitle': 'Clients who trust our judgment.',
      'booking.whatsappMessage': 'Hello, I would like to book a legal consultation.',
      'booking.mailtoSubject': 'Legal inquiry',
      'phone.whatsappMessage': 'Hello, I would like information about legal advice.',
    },
  },
  medical: {
    es: {
      'placeholders.psychologistName': 'Nombre del profesional',
      'placeholders.specialty': 'Especialidad médica',
      'placeholders.aboutTagline': 'Atención cercana y profesional para tu bienestar.',
      'nav.bookAppointment': 'Agendar cita',
      'contact.subtitle': 'Agenda tu consulta. Estoy para ayudarte a cuidar tu salud.',
      'services.defaultTitle': 'Servicios y consultas',
      'services.defaultIntro': 'Atenciones y tratamientos disponibles.',
      'gallery.defaultIntro': 'Conoce el consultorio y el espacio de atención.',
      'testimonials.subtitle': 'Experiencias de pacientes.',
      'booking.whatsappMessage': 'Hola, me gustaría agendar una cita médica.',
      'booking.mailtoSubject': 'Cita médica',
      'phone.whatsappMessage': 'Hola, me gustaría información sobre la consulta.',
    },
    en: {
      'placeholders.psychologistName': 'Professional name',
      'placeholders.specialty': 'Medical specialty',
      'placeholders.aboutTagline': 'Close, professional care for your wellbeing.',
      'nav.bookAppointment': 'Book appointment',
      'contact.subtitle': 'Schedule a visit. I am here to help you care for your health.',
      'services.defaultTitle': 'Services and consults',
      'services.defaultIntro': 'Available care and treatments.',
      'gallery.defaultIntro': 'See the clinic and care space.',
      'testimonials.subtitle': 'Patient experiences.',
      'booking.whatsappMessage': 'Hello, I would like to book a medical appointment.',
      'booking.mailtoSubject': 'Medical appointment',
      'phone.whatsappMessage': 'Hello, I would like information about the consultation.',
    },
  },
  beauty: {
    es: {
      'placeholders.psychologistName': 'Nombre del profesional',
      'placeholders.specialty': 'Servicio o especialidad',
      'placeholders.aboutTagline': 'Belleza y bienestar con un trato personalizado.',
      'nav.bookAppointment': 'Reservar cita',
      'contact.subtitle': 'Reserva tu espacio. Cuéntanos qué servicio te interesa.',
      'services.defaultTitle': 'Servicios',
      'services.defaultIntro': 'Tratamientos y experiencias pensadas para ti.',
      'gallery.defaultIntro': 'Resultados, espacios y ambiente.',
      'testimonials.subtitle': 'Lo que dicen nuestros clientes.',
      'booking.whatsappMessage': 'Hola, me gustaría reservar una cita.',
      'booking.mailtoSubject': 'Reserva de cita',
      'phone.whatsappMessage': 'Hola, me gustaría información sobre sus servicios.',
      'catalog.defaultTitle': 'Paquetes y productos',
      'catalog.defaultIntro': 'Explora opciones y elige lo que mejor te queda.',
    },
    en: {
      'placeholders.psychologistName': 'Professional name',
      'placeholders.specialty': 'Service or specialty',
      'placeholders.aboutTagline': 'Beauty and wellness with a personal touch.',
      'nav.bookAppointment': 'Book appointment',
      'contact.subtitle': 'Reserve your spot. Tell us which service you want.',
      'services.defaultTitle': 'Services',
      'services.defaultIntro': 'Treatments and experiences designed for you.',
      'gallery.defaultIntro': 'Results, spaces, and atmosphere.',
      'testimonials.subtitle': 'What our clients say.',
      'booking.whatsappMessage': 'Hello, I would like to book an appointment.',
      'booking.mailtoSubject': 'Appointment booking',
      'phone.whatsappMessage': 'Hello, I would like information about your services.',
      'catalog.defaultTitle': 'Packages and products',
      'catalog.defaultIntro': 'Explore options and find what fits you best.',
    },
  },
  fitness: {
    es: {
      'placeholders.psychologistName': 'Nombre del coach',
      'placeholders.specialty': 'Enfoque o disciplina',
      'placeholders.aboutTagline': 'Entrena con claridad, constancia y un plan a tu medida.',
      'nav.bookAppointment': 'Agendar sesión',
      'contact.subtitle': 'Escríbeme para agendar una sesión o consulta inicial.',
      'services.defaultTitle': 'Programas y servicios',
      'services.defaultIntro': 'Entrenamientos y acompañamiento para tus metas.',
      'gallery.defaultIntro': 'Entrenamientos, espacios y resultados.',
      'testimonials.subtitle': 'Historias de progreso.',
      'booking.whatsappMessage': 'Hola, me gustaría agendar una sesión de entrenamiento.',
      'booking.mailtoSubject': 'Sesión de entrenamiento',
      'phone.whatsappMessage': 'Hola, me gustaría información sobre entrenamiento.',
      'catalog.defaultTitle': 'Planes',
      'catalog.defaultIntro': 'Elige el plan que mejor se adapte a tu ritmo.',
    },
    en: {
      'placeholders.psychologistName': 'Coach name',
      'placeholders.specialty': 'Focus or discipline',
      'placeholders.aboutTagline': 'Train with clarity, consistency, and a plan made for you.',
      'nav.bookAppointment': 'Book session',
      'contact.subtitle': 'Write me to schedule a session or intro consult.',
      'services.defaultTitle': 'Programs and services',
      'services.defaultIntro': 'Training and support for your goals.',
      'gallery.defaultIntro': 'Workouts, spaces, and progress.',
      'testimonials.subtitle': 'Progress stories.',
      'booking.whatsappMessage': 'Hello, I would like to book a training session.',
      'booking.mailtoSubject': 'Training session',
      'phone.whatsappMessage': 'Hello, I would like information about training.',
      'catalog.defaultTitle': 'Plans',
      'catalog.defaultIntro': 'Choose the plan that fits your pace.',
    },
  },
  education: {
    es: {
      'placeholders.psychologistName': 'Nombre del educador',
      'placeholders.specialty': 'Área o materia',
      'placeholders.aboutTagline': 'Aprende con método claro y acompañamiento cercano.',
      'nav.bookAppointment': 'Solicitar información',
      'contact.subtitle': 'Escríbeme para conocer fechas, modalidades o una sesión de prueba.',
      'services.defaultTitle': 'Programas y cursos',
      'services.defaultIntro': 'Formación, talleres y acompañamiento educativo.',
      'gallery.defaultIntro': 'Clases, materiales y comunidad de aprendizaje.',
      'testimonials.subtitle': 'Lo que dicen alumnos y familias.',
      'booking.whatsappMessage': 'Hola, me gustaría información sobre los cursos.',
      'booking.mailtoSubject': 'Información de cursos',
      'phone.whatsappMessage': 'Hola, me gustaría información educativa.',
      'catalog.defaultTitle': 'Cursos y materiales',
      'catalog.defaultIntro': 'Explora opciones de aprendizaje disponibles.',
    },
    en: {
      'placeholders.psychologistName': 'Educator name',
      'placeholders.specialty': 'Subject or focus',
      'placeholders.aboutTagline': 'Learn with a clear method and close support.',
      'nav.bookAppointment': 'Request info',
      'contact.subtitle': 'Write me about dates, formats, or a trial session.',
      'services.defaultTitle': 'Programs and courses',
      'services.defaultIntro': 'Training, workshops, and educational support.',
      'gallery.defaultIntro': 'Classes, materials, and learning community.',
      'testimonials.subtitle': 'What students and families say.',
      'booking.whatsappMessage': 'Hello, I would like information about the courses.',
      'booking.mailtoSubject': 'Course information',
      'phone.whatsappMessage': 'Hello, I would like education-related information.',
      'catalog.defaultTitle': 'Courses and materials',
      'catalog.defaultIntro': 'Explore available learning options.',
    },
  },
  ecommerce: {
    es: {
      'placeholders.psychologistName': 'Nombre de la marca',
      'placeholders.specialty': 'Categoría o enfoque',
      'placeholders.aboutTagline': 'Productos pensados para acompañarte en el día a día.',
      'nav.bookAppointment': 'Contactar',
      'contact.subtitle': '¿Dudas sobre un producto o pedido? Escríbenos, estamos para ayudarte.',
      'services.defaultTitle': 'Cómo trabajamos',
      'services.defaultIntro': 'Envíos, atención y promesa de marca.',
      'gallery.defaultIntro': 'Productos, detalle y detrás de la marca.',
      'testimonials.subtitle': 'Opiniones de clientes.',
      'booking.whatsappMessage': 'Hola, me gustaría información sobre un producto.',
      'booking.mailtoSubject': 'Consulta de producto',
      'phone.whatsappMessage': 'Hola, me gustaría información de la tienda.',
      'catalog.defaultTitle': 'Catálogo',
      'catalog.defaultIntro': 'Explora el catálogo y encuentra lo que buscas.',
      'catalog.viewMore': 'Ver producto',
    },
    en: {
      'placeholders.psychologistName': 'Brand name',
      'placeholders.specialty': 'Category or focus',
      'placeholders.aboutTagline': 'Products designed to support everyday life.',
      'nav.bookAppointment': 'Contact us',
      'contact.subtitle': 'Questions about a product or order? Write us — we are here to help.',
      'services.defaultTitle': 'How we work',
      'services.defaultIntro': 'Shipping, support, and brand promise.',
      'gallery.defaultIntro': 'Products, details, and behind the brand.',
      'testimonials.subtitle': 'Customer reviews.',
      'booking.whatsappMessage': 'Hello, I would like information about a product.',
      'booking.mailtoSubject': 'Product inquiry',
      'phone.whatsappMessage': 'Hello, I would like shop information.',
      'catalog.defaultTitle': 'Catalog',
      'catalog.defaultIntro': 'Browse the catalog and find what you need.',
      'catalog.viewMore': 'View product',
    },
  },
};

export function getVerticalLabelOverrides(vertical, language = 'es') {
  const id = normalizeVertical(vertical);
  if (id === DEFAULT_VERTICAL) return {};
  const lang = language === 'en' ? 'en' : 'es';
  return VERTICAL_LABEL_OVERRIDES[id]?.[lang] ?? VERTICAL_LABEL_OVERRIDES[id]?.es ?? {};
}
